# Generated by Django 3.1.7 on 2021-05-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBIReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50, verbose_name="Power BI report's id")),
                ('group_id', models.CharField(max_length=50, verbose_name="Power BI report's group id")),
                ('report_name', models.CharField(max_length=30, verbose_name='report name which is received from embed request')),
                ('api_client_id', models.CharField(max_length=50, verbose_name='Azure API client id')),
                ('api_secrete', models.CharField(max_length=50, verbose_name='Azure API client secrete')),
            ],
        ),
        migrations.CreateModel(
            name='PowerBIRSL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=30, verbose_name='RSL role name')),
                ('user_name', models.EmailField(max_length=254, verbose_name='RSL user name(Azure email account)')),
                ('dataset_id', models.CharField(max_length=50, verbose_name="Azure user's dataset(tenant) id")),
            ],
        ),
    ]
