# Generated by Django 3.1.7 on 2021-05-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerbireport',
            name='api_client_id',
            field=models.CharField(help_text='Azure API client id', max_length=50),
        ),
        migrations.AlterField(
            model_name='powerbireport',
            name='api_secrete',
            field=models.CharField(help_text='Azure API client secrete', max_length=50),
        ),
        migrations.AlterField(
            model_name='powerbireport',
            name='group_id',
            field=models.CharField(help_text="Power BI report's group id(or workspace id)", max_length=50),
        ),
        migrations.AlterField(
            model_name='powerbireport',
            name='report_id',
            field=models.CharField(help_text="Power BI report's id", max_length=50),
        ),
        migrations.AlterField(
            model_name='powerbireport',
            name='report_name',
            field=models.CharField(help_text='report name which is received from embed request', max_length=30),
        ),
        migrations.AlterField(
            model_name='powerbirsl',
            name='dataset_id',
            field=models.CharField(help_text="Azure user's dataset id", max_length=50),
        ),
        migrations.AlterField(
            model_name='powerbirsl',
            name='role_name',
            field=models.CharField(help_text='RSL role name', max_length=30),
        ),
        migrations.AlterField(
            model_name='powerbirsl',
            name='user_name',
            field=models.EmailField(help_text='RSL user name(Azure email account)', max_length=254),
        ),
    ]
